create table public.profiles (user_id uuid primary key references auth.users on delete cascade, settings jsonb not null default '{"timezone":"America/Phoenix","quietStart":"22:00","quietEnd":"08:00"}');
create table public.agents (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, name text not null check(length(name) between 1 and 100), avatar text not null default 'amber', personality text not null default '', worldview text not null default '', background text not null default '', expertise text not null default '', instructions text not null default '', voice text not null default 'Kore', memories text not null default '', permissions jsonb not null default '{"documents":true,"memory":true,"search":false,"scheduled":false}', project_scope uuid[] not null default '{}', archived boolean not null default false, unique(id,user_id));
create table public.projects (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users on delete cascade, name text not null check(length(name) between 1 and 100), archived boolean not null default false, created_at timestamptz not null default now(), unique(id,user_id));
create table public.memberships (project_id uuid not null,agent_id uuid not null,user_id uuid not null default auth.uid() references auth.users on delete cascade,primary key(project_id,agent_id),foreign key(project_id,user_id) references public.projects(id,user_id) on delete cascade,foreign key(agent_id,user_id) references public.agents(id,user_id) on delete cascade);
create table public.requests (id uuid primary key, user_id uuid not null default auth.uid() references auth.users on delete cascade,project_id uuid not null, status text not null default 'pending' check(status in ('pending','done','failed','cancelled')),created_at timestamptz not null default now(), foreign key(project_id,user_id) references public.projects(id,user_id) on delete cascade);
create unique index one_pending_turn on public.requests(project_id) where status='pending';
create table public.messages (id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users on delete cascade,project_id uuid not null,agent_id uuid,role text not null check(role in ('user','assistant')),content text not null check(length(content)<=24000),sources jsonb not null default '[]',created_at timestamptz not null default now(),request_id uuid references public.requests on delete set null,foreign key(project_id,user_id) references public.projects(id,user_id) on delete cascade,foreign key(agent_id,user_id) references public.agents(id,user_id) on delete set null (agent_id));
create table public.documents (id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users on delete cascade,project_id uuid not null,name text not null,storage_path text,status text not null default 'processing' check(status in ('processing','ready','error')),error text,chunks jsonb not null default '[]',created_at timestamptz not null default now(),foreign key(project_id,user_id) references public.projects(id,user_id) on delete cascade);
create table public.jobs (id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users on delete cascade,project_id uuid not null,agent_id uuid,title text not null,kind text not null check(kind in ('reminder','ideas','research')),topic text not null,cron text not null,timezone text not null,next_run timestamptz not null,enabled boolean not null default true,notify boolean not null default false,allowance integer not null default 10 check(allowance between 1 and 30),last_error text,foreign key(project_id,user_id) references public.projects(id,user_id) on delete cascade,foreign key(agent_id,user_id) references public.agents(id,user_id) on delete cascade);
create table public.job_runs (id uuid primary key default gen_random_uuid(),job_id uuid not null references public.jobs on delete cascade,user_id uuid not null references auth.users on delete cascade,scheduled_at timestamptz not null,status text not null default 'running',attempts integer not null default 1,lease_until timestamptz not null default now()+interval '2 minutes',error text,created_at timestamptz not null default now(),unique(job_id,scheduled_at));
create table public.inbox (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,job_id uuid not null references public.jobs on delete cascade,run_id uuid not null unique references public.job_runs on delete cascade,title text not null,body text not null,why text not null,sources jsonb not null default '[]',read boolean not null default false,created_at timestamptz not null default now());
create table public.usage (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,kind text not null,model text not null default '',status text not null default 'reserved',input_tokens integer,output_tokens integer,duration_ms integer,created_at timestamptz not null default now());
create index usage_by_user_day on public.usage(user_id,created_at);
create table public.music_feedback (id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users on delete cascade,track_id bigint not null,context text not null,feedback text not null check(feedback in ('liked','disliked','wrong moment')),created_at timestamptz not null default now());
create table public.system_config (id boolean primary key default true check(id),ai_enabled boolean not null default true,user_daily_limit integer not null default 40 check(user_daily_limit between 1 and 1000),global_daily_limit integer not null default 400 check(global_daily_limit between 1 and 100000));
insert into public.system_config(id) values(true);
-- Never trust an agent prompt or client filter as authorization.
do $$ declare t text; begin foreach t in array array['profiles','agents','projects','memberships','requests','messages','documents','jobs','job_runs','inbox','usage','music_feedback'] loop execute format('alter table public.%I enable row level security',t);execute format('create policy own_read on public.%I for select to authenticated using (user_id=auth.uid())',t);end loop;end $$;
do $$ declare t text; begin foreach t in array array['profiles','agents','projects','memberships','messages','documents','jobs','music_feedback'] loop execute format('create policy own_insert on public.%I for insert to authenticated with check (user_id=auth.uid())',t);execute format('create policy own_update on public.%I for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid())',t);execute format('create policy own_delete on public.%I for delete to authenticated using (user_id=auth.uid())',t);end loop;end $$;
create policy inbox_read_update on public.inbox for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
alter table public.system_config enable row level security;
-- Usage mutations are privileged. Failed and cancelled attempts consume call allowance.
create function public.reserve_usage(p_user uuid,p_kind text,p_model text,p_count integer) returns uuid[] language plpgsql security definer set search_path=public as $$
declare limits system_config; result uuid[]='{}'; item uuid; begin
if current_user<>'postgres' and auth.role()<>'service_role' then raise exception 'service role required';end if;
if p_count<1 or p_count>3 then raise exception 'invalid call count';end if;
perform pg_advisory_xact_lock(914257);
select * into limits from system_config where id=true;
if p_kind<>'music' and not limits.ai_enabled then raise exception 'AI is paused by the owner';end if;
if (select count(*) from usage where user_id=p_user and created_at>=date_trunc('day',now()))+p_count>limits.user_daily_limit then raise exception 'daily user allowance reached';end if;
if (select count(*) from usage where created_at>=date_trunc('day',now()))+p_count>limits.global_daily_limit then raise exception 'daily app allowance reached';end if;
for i in 1..p_count loop insert into usage(user_id,kind,model) values(p_user,p_kind,p_model) returning id into item;result=array_append(result,item);end loop;return result;end $$;
revoke all on function public.reserve_usage(uuid,text,text,integer) from public,anon,authenticated;
grant execute on function public.reserve_usage(uuid,text,text,integer) to service_role;
create function public.claim_jobs() returns setof public.job_runs language plpgsql security definer set search_path=public as $$
declare j jobs; r job_runs; begin
for j in select * from jobs where enabled and next_run<=now() order by next_run for update skip locked limit 5 loop
if (select count(*) from job_runs where job_id=j.id and status='done' and created_at>=date_trunc('month',now()))>=j.allowance then continue;end if;
insert into job_runs(job_id,user_id,scheduled_at) values(j.id,j.user_id,j.next_run) on conflict(job_id,scheduled_at) do nothing returning * into r;
if r.id is null then update job_runs set status='running',attempts=attempts+1,lease_until=now()+interval '2 minutes' where job_id=j.id and scheduled_at=j.next_run and lease_until<now() and status in ('running','retry') and attempts<3 returning * into r;end if;
if r.id is not null then return next r;end if;
end loop;end $$;
revoke all on function public.claim_jobs() from public,anon,authenticated;
grant execute on function public.claim_jobs() to service_role;
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(user_id) values(new.id);return new;end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
-- Private storage; paths begin with the authenticated user's UUID.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('cast-private','cast-private',false,5242880,array['image/png','image/jpeg','image/webp','application/pdf','text/plain','text/markdown']);
create policy own_files_read on storage.objects for select to authenticated using(bucket_id='cast-private' and (storage.foldername(name))[1]=auth.uid()::text);
create policy own_files_insert on storage.objects for insert to authenticated with check(bucket_id='cast-private' and (storage.foldername(name))[1]=auth.uid()::text);
create policy own_files_delete on storage.objects for delete to authenticated using(bucket_id='cast-private' and (storage.foldername(name))[1]=auth.uid()::text);
